### PR TITLE
Branch for 2.1.x series

### PR DESCRIPTION
**Pull request by spikymonkey**

### CODE REVIEW

**Comment by Albertoimpl** [comment]
To make it consistent with how we did it in the past, can you also update the dependabot and the main readme? https://github.com/spring-cloud/spring-cloud-app-broker/commit/7303c938c9eb956dc567130bc5083181f39c0a3b

**Comment by spikymonkey** [comment]
Ah yes of course! I've updated the dependabot config, and created a new section in the README, but since we've just branched I think we'll need to leave updating the key dependency versions in there until we know more.

**Review by Albertoimpl — APPROVED** [review]
Thanks!

**Comment by spikymonkey** [comment]
Thanks @Albertoimpl!

**Pull request merged**
