### PR TITLE
Improving CF deployer documentation

### PR DESCRIPTION
**Pull request by Albertoimpl**
Adding stack as a suported property

### CODE REVIEW

**Review by spikymonkey — DISMISSED** [review]
Thanks @Albertoimpl! Should we take the opportunity to sort the rows in this table? It feels a bit random at the moment.

**Comment by Albertoimpl** [comment]
I like the idea, should we introduce sub-groups or go with alphabetical order @spikymonkey?

**Comment by spikymonkey** [comment]
> I like the idea, should we introduce sub-groups or go with alphabetical order @spikymonkey?

Maybe alphabetical for now, since it's a fairly short list? We can always add sub groups later if we want to.

**Comment by Albertoimpl** [comment]
Done, thanks @spikymonkey!

**Review by spikymonkey — APPROVED** [review]
Cool, thanks @Albertoimpl!

**Pull request merged**
